#!/usr/bin/env python3
import subprocess


def main():
    input_file = open('v2s.txt', 'r')
    output_file = open('output.txt', 'w')
    lines = input_file.readlines()
    output_lines = []
    for line in lines:
        timecode, command = line.split('\t')
        output_image_path = command.split()[-1]
        subprocess.call(command, shell=True)

        output_lines.append(timecode + ' ' + output_image_path + '\n')

    output_file.writelines(output_lines)
    input_file.close()
    output_file.close()


if __name__ == '__main__':
    main()
