#!/usr/bin/env python3
import logging
import os
import shutil
import sys


# 00:00:00
def to_s(t):
  return int(t[:2]) * 3600 + int(t[3:5]) * 60 + int(t[6:])


if len(sys.argv) < 3:
  logging.error("arv1: s2iout, argv2: 出力先フォルダ")
  exit(1)

os.makedirs(sys.argv[2], exist_ok=True)

s2iout = open(sys.argv[1], 'r')
lines = s2iout.readlines()

x = lines[0].split()
i = to_s(x[0])  # 最初は00:00:00なので0に初期化されるはず
olf_f = x[1]

for line in lines:
  tc, f = line.split()
  t = to_s(tc)
  if i < t:
    for j in range(t - i):
      new_file_name = os.path.join(sys.argv[2], f"out{i}.png")
      shutil.copy(old_f, new_file_name)
      i = i + 1
  old_f = f

# 上のループだと最後の画像が書き出されないので↓で書き出す
new_file_name = os.path.join(sys.argv[2], f"out{i}.png")
shutil.copy(f, new_file_name)

s2iout.close()
