#!/usr/bin/env python3
import sys

r = ""
l = ""
t = ""
for s in sys.argv[1].split():
  t = s if s[:2] != "l:" and s[:2] != "r:" else t
  l = s[2:] if s[:2] == "l:" else l
  r = s[2:] if s[:2] == "r:" else r

if l != "" and r != "":
  print(f"{t}\tsaeota -l {l} -r {r}")
elif l != "" and r == "":
  print(f"{t}\tsaeota -l {l}")
elif l == "" and r != "":
  print(f"{t}\tsaeota -r {r}")
